import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import { Geist_Mono, Public_Sans } from "next/font/google";
import { cn } from "@/lib/utils";

const publicSansHeading = Public_Sans({subsets:['latin'],variable:'--font-heading'});

const geistMono = Geist_Mono({subsets:['latin'],variable:'--font-mono'});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en" suppressHydrationWarning className={cn("font-mono", geistMono.variable, publicSansHeading.variable)}
        >
        <body>
        {children}
        </body>
        </html>
    );
}
